require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemTypesController do

  # This should return the minimal set of attributes required to create a valid
  # ItemType. As you add validations to ItemType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all item_types as @item_types" do
      item_type = ItemType.create! valid_attributes
      get :index
      assigns(:item_types).should eq([item_type])
    end
  end

  describe "GET show" do
    it "assigns the requested item_type as @item_type" do
      item_type = ItemType.create! valid_attributes
      get :show, :id => item_type.id.to_s
      assigns(:item_type).should eq(item_type)
    end
  end

  describe "GET new" do
    it "assigns a new item_type as @item_type" do
      get :new
      assigns(:item_type).should be_a_new(ItemType)
    end
  end

  describe "GET edit" do
    it "assigns the requested item_type as @item_type" do
      item_type = ItemType.create! valid_attributes
      get :edit, :id => item_type.id.to_s
      assigns(:item_type).should eq(item_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ItemType" do
        expect {
          post :create, :item_type => valid_attributes
        }.to change(ItemType, :count).by(1)
      end

      it "assigns a newly created item_type as @item_type" do
        post :create, :item_type => valid_attributes
        assigns(:item_type).should be_a(ItemType)
        assigns(:item_type).should be_persisted
      end

      it "redirects to the created item_type" do
        post :create, :item_type => valid_attributes
        response.should redirect_to(ItemType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved item_type as @item_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemType.any_instance.stub(:save).and_return(false)
        post :create, :item_type => {}
        assigns(:item_type).should be_a_new(ItemType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemType.any_instance.stub(:save).and_return(false)
        post :create, :item_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested item_type" do
        item_type = ItemType.create! valid_attributes
        # Assuming there are no other item_types in the database, this
        # specifies that the ItemType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ItemType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => item_type.id, :item_type => {'these' => 'params'}
      end

      it "assigns the requested item_type as @item_type" do
        item_type = ItemType.create! valid_attributes
        put :update, :id => item_type.id, :item_type => valid_attributes
        assigns(:item_type).should eq(item_type)
      end

      it "redirects to the item_type" do
        item_type = ItemType.create! valid_attributes
        put :update, :id => item_type.id, :item_type => valid_attributes
        response.should redirect_to(item_type)
      end
    end

    describe "with invalid params" do
      it "assigns the item_type as @item_type" do
        item_type = ItemType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemType.any_instance.stub(:save).and_return(false)
        put :update, :id => item_type.id.to_s, :item_type => {}
        assigns(:item_type).should eq(item_type)
      end

      it "re-renders the 'edit' template" do
        item_type = ItemType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemType.any_instance.stub(:save).and_return(false)
        put :update, :id => item_type.id.to_s, :item_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested item_type" do
      item_type = ItemType.create! valid_attributes
      expect {
        delete :destroy, :id => item_type.id.to_s
      }.to change(ItemType, :count).by(-1)
    end

    it "redirects to the item_types list" do
      item_type = ItemType.create! valid_attributes
      delete :destroy, :id => item_type.id.to_s
      response.should redirect_to(item_types_url)
    end
  end

end
